const data = [
  {
    id: 1,
    name: "Product A",
    likes: 120,
    shares: 45,
    comments: 30,
    followers: 15000,
    category: "Tech",
    location: "USA",
  },
  {
    id: 2,
    name: "Product B",
    likes: 200,
    shares: 75,
    comments: 50,
    followers: 25000,
    category: "Fashion",
    location: "France",
  },
  {
    id: 3,
    name: "Product C",
    likes: 90,
    shares: 30,
    comments: 25,
    followers: 18000,
    category: "Food",
    location: "Italy",
  },
  {
    id: 4,
    name: "Product D",
    likes: 300,
    shares: 100,
    comments: 70,
    followers: 40000,
    category: "Lifestyle",
    location: "Canada",
  },
  {
    id: 5,
    name: "Product E",
    likes: 150,
    shares: 60,
    comments: 40,
    followers: 22000,
    category: "Travel",
    location: "Australia",
  },
];

export default data;
